

# from "diamond standard nexus structure V2.docx"
METADATA = {
    '/entry': 'NXentry',
    '/entry/instrument': 'NXinstrument',
    '/entry/instrument/name': 'I16',
    '/entry/instrument/source': 'NXsource',
    '/entry/instrument/source/name': 'Diamond Light Source',
    '/entry/instrument/source/type': 'Synchrotron X-ray Source',
    '/entry/instrument/source/probe': 'x-ray',
    '/entry/instrument/source/current': 'link to ring current',
    '/entry/instrument/insertion_device': 'NXinsertion_device',
    '/entry/instrument/insertion_device/gap': 'link to IDgap',
    '/entry/instrument/monochromator': 'NXmonochromator',
    '/entry/instrument/monochromator/energy': '8 keV',
    '/entry/sample': 'NXsample',
    '/entry/sample/name': 'name',
    '/entry/sample/depends_on': 'name',
    '/entry/sample/chemical_formula': '',
    '/entry/sample/temperature': '10 K',
    '/entry/sample/electric_field': '0 V',
    '/entry/sample/magnetic_field': '0 T',
    '/entry/sample/pressure': '0 Pa',
    'entry/sample/transformations': 'NXtransformations',
    '/entry/sample/beam': 'NXbeam',
    '/entry/sample/beam/incident_energy': '8 keV',
    '/entry/sample/beam/flux': '10^13 ph/s',
    '/entry/sample/beam/extent': '250 x 30 um^2',
    '/entry/sample/beam/incident_beam_divergence': '30 x 10 nm',
    '/entry/sample/beam/incident_polarization': 'vector',
    '/entry/sample/beam/incident_polarization_stokes': 'vector',
    '/entry/sample/surface_hkl': 'vector',
    '/entry/sample/orientation_matrix': '3x3 array',
    '/entry/sample/ub_matrix': '3x3 array',
    '/entry/sample/unit_cell': '6x1 array',
    '/entry/sample/diffcalc': 'NXnote',
    '/entry/sample/diffcalc/description': 'Data used by diffcalc application',
    '/entry/sample/diffcalc/type': 'application/json',
    '/entry/sample/diffcalc/data': '{}',
    '/entry/title': 'scancn x 0.01 3 pil 0.1 roi2',
    '/entry/experiment_identifier': 'mm12345-1',
    '/entry/start_time': '2024-12-24 10:00',
    '/entry/end_time': '2024-12-24 10:01',
    '/entry/end_time_estimated': '2024-12-24 10:01',
    '/entry/program_name': 'GDA',
    '/entry/definition': 'NXmx',
    '/entry/entry_identifier': '123456',
    # '/entry/subentry': 'NXsubentry',
    '/entry/diamond_scan': 'NXCollection',
    '/entry/diamond_scan/keys': 'NXCollection',
    '/entry/diamond_scan/uniqueKeys': 'int',
    '/entry/diamond_scan/point_start_times': '',
    '/entry/diamond_scan/point_end_times': '',
    '/entry/diamond_scan/scan_command': 'scan x 1 10 1 pil3_100k 1',
    '/entry/diamond_scan/scan_dead_time': '',
    '/entry/diamond_scan/scan_dead_time_percent': '',
    '/entry/diamond_scan/scan_estimated_duration': '',
    '/entry/diamond_scan/scan_finished': '1',
    '/entry/diamond_scan/scan_rank': '1',
    '/entry/diamond_scan/scan_shape': '10',
    '/entry/diamond_scan/scan_fields': ['hkl.h', 'hkl.k', 'hkl.l', 'pil3.roi_sum'],
    '/entry/diamond_scan/user_command': '',
    '/entry/diamond_scan/called_by': '',
    '/entry/diamond_scan/script': 'NXnote',
    '/entry/measurement': 'NXdata',
    '/entry/measurement/x': 'link',
    '/entry/measurement/count_time': 'link',
    '/entry/instrument/s5': 'NXslit',
    '/entry/instrument/s5/x_gap': '0.1 mm',
    '/entry/instrument/s5/y_gap': '0.1 mm',
    '/entry/instrument/s5/depends_on': 's5transformations/x_centre',
    '/entry/instrument/s5/s5transformations': 'NXtransformations',
    '/entry/instrument/s5/s5transformations/x_centre': '0.0 mm',
    '/entry/instrument/s5/s5transformations/y_centre': '0.0 mm',
    '/entry/instrument/s5/s5transformations/z_centre': '0.0 mm',
}

NXDETECTOR_DATA = {
    "data": 'nd array',
    "sensor_material": 'char',
    "sensor_thickness": 'float',
    "polarization_analyser_jones_matrix": '',
    "module": 'NXdetector_module',
    "module/data_origin": 'int',
    "module/data_size": 'int',
    "module/fast_pixel_direction": 'int',
    "module/slow_pixel_direction": 'int',
}

NXENTRY_ATTRIBUTES = {
    'default': b'NXdata'
}

NXDATA_ATTRIBUTES = {
    'signal': b'roi2_sum',
    'axes': [b'k',],
    # 'auxiliary_signals': [b'count_time', b'total', b'max_val'],
}

DATASET_ATTRIBUTES = {
    # 'decimals': 8,
    # 'units': b'r.l.u',
    'local_name': b'hkl.h',
}

ATTRIBUTES = {
    '/entry/measurement': NXDATA_ATTRIBUTES,
    '/entry/measurement/h': DATASET_ATTRIBUTES,
    '/entry/instrument/source/current': {'units': b'mA'},
    '/entry/instrument/insertion_device/gap': {'units': b'mm'},
    '/entry/instrument/monochromator/energy': {'units': b'keV'},
    '/entry/sample/temperature': {'units': b'K'},
    '/entry/sample/electric_field': {'units': b'V'},
    '/entry/sample/magnetic_field': {'units': b'T'},
    '/entry/sample/pressure': {'units': b'Pa'},
    '/entry/sample/beam/incident_energy': {'units': b'keV'},
    '/entry/sample/beam/flux': {'units': b'ph/s'},
    '/entry/sample/beam/incident_beam_size': {'units': b'um'},
    '/entry/sample/beam/incident_beam_divergence': {'units': b'nm'},
}
